from flask import Flask, request, jsonify, send_file
import os
from backend_logic import ForgeryDetector
from aadhaar_logic import AadhaarAnalyzer
from flask_cors import CORS
import uuid
import hashlib
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

app = Flask(__name__)
CORS(app)

UPLOAD_FOLDER = 'uploads'
CERT_FOLDER = 'certificates'
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
if not os.path.exists(CERT_FOLDER):
    os.makedirs(CERT_FOLDER)

# Initialize Engines
aadhaar_engine = AadhaarAnalyzer()

def calculate_sha256(filepath):
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        # Read and update hash string value in blocks of 4K
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def generate_certificate(cert_id, filename, file_hash, analysis_type, timestamp):
    cert_path = os.path.join(CERT_FOLDER, f"{cert_id}.pdf")
    c = canvas.Canvas(cert_path, pagesize=letter)
    width, height = letter

    # Border
    c.setStrokeColor(colors.darkblue)
    c.setLineWidth(5)
    c.rect(30, 30, width-60, height-60)

    # Header
    c.setFont("Helvetica-Bold", 30)
    c.drawCentredString(width/2, height - 100, "CERTIFICATE OF ANALYSIS")
    
    c.setFont("Helvetica", 12)
    c.drawCentredString(width/2, height - 130, "Sicario Forensic Document Analyzer")

    # Content
    y_pos = height - 200
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y_pos, "Reference ID:")
    c.setFont("Helvetica", 14)
    c.drawString(250, y_pos, cert_id)
    
    y_pos -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y_pos, "File Name:")
    c.setFont("Helvetica", 14)
    c.drawString(250, y_pos, filename)

    y_pos -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y_pos, "Analysis Type:")
    c.setFont("Helvetica", 14)
    c.drawString(250, y_pos, analysis_type)

    y_pos -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y_pos, "Timestamp:")
    c.setFont("Helvetica", 14)
    c.drawString(250, y_pos, timestamp)

    y_pos -= 60
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y_pos, "SHA-256 Secure Hash:")
    c.setFont("Courier", 10)
    c.drawString(100, y_pos - 20, file_hash)

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width/2, 60, "This document certifies that the above file has undergone forensic analysis.")
    c.drawCentredString(width/2, 45, "Generated by Sicario Secure Layer")

    c.save()
    return f"{cert_id}.pdf"

@app.route('/analyze', methods=['POST'])
def analyze_document():
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400
    
    file = request.files['file']
    doc_type = request.form.get('doc_type', 'marksheet')
    
    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400
    
    if file:
        filename = f"{uuid.uuid4()}_{file.filename}"
        filepath = os.path.join(UPLOAD_FOLDER, filename)
        file.save(filepath)
        
        try:
            # --- SECURITY LAYER: HASHING ---
            file_hash = calculate_sha256(filepath)
            cert_id = str(uuid.uuid4()).upper()
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            response_data = {}
            
            # --- ROUTING LOGIC BASED ON DOC TYPE ---
            
            if doc_type == 'aadhaar':
                # Use Aadhaar Logic
                result = aadhaar_engine.analyze(filepath)
                
                response_data = {
                    "filename": file.filename,
                    "checks": {
                        "Aadhaar Number": {
                            "status": result["status"],
                            "details": result["details"]
                        },
                        "Structural Check": {
                            "status": "Pass" if result["verhoeff_valid"] else "Fail",
                            "details": "Verhoeff Algorithm Validation"
                        },
                         "Database Check": {
                            "status": "Pass" if result["db_valid"] else "Fail",
                            "details": "ID existence in authorized DB"
                        }
                    },
                    "ela_url": None
                }

            elif doc_type == 'bills':
                # --- MOCK DATA FOR BILLS ---
                response_data = {
                    "filename": file.filename,
                    "checks": {
                        "Digital Tampering (ELA)": {
                            "status": "Fail",
                            "details": "High compression artifacts detected near 'Total Amount' field."
                        },
                        "Metadata Analysis": {
                            "status": "Warn",
                            "details": "Software: 'Adobe Photoshop 2024' found in EXIF tags."
                        },
                        "Font Consistency": {
                            "status": "Fail",
                            "details": "Detected multiple font families (Arial, Times New Roman) in same line."
                        },
                         "Tax Calculation": {
                            "status": "Pass",
                            "details": "GST 18% calculation is mathematically correct."
                        }
                    },
                    "ela_url": None 
                }
                
            else:
                # Default: Forgery Detection (Marksheet)
                detector = ForgeryDetector(filepath)
                detector.perform_ela(output_dir=UPLOAD_FOLDER)
                detector.check_metadata()
                detector.verify_logical_consistency()
                
                response_data = detector.report_data
                if response_data.get("ela_path"):
                    response_data["ela_url"] = f"http://localhost:5000/uploads/{response_data['ela_path']}"

            # --- GENERATE CERTIFICATE ---
            cert_filename = generate_certificate(cert_id, file.filename, file_hash, doc_type.upper(), timestamp)
            
            # Append Security Data
            response_data["security"] = {
                "file_hash": file_hash,
                "cert_id": cert_id,
                "cert_url": f"http://localhost:5000/certificates/{cert_filename}"
            }

            return jsonify(response_data)
            
        except Exception as e:
            return jsonify({"error": str(e)}), 500

@app.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_file(os.path.join(UPLOAD_FOLDER, filename))

@app.route('/certificates/<filename>')
def serve_certificate(filename):
    return send_file(os.path.join(CERT_FOLDER, filename))

if __name__ == '__main__':
    print("Starting Backend Server on port 5000...")
    app.run(debug=True, host='0.0.0.0', port=5000)
