from flask import Flask, request, jsonify, send_file
import os
from backend_logic import ForgeryDetector
from aadhaar_logic import AadhaarAnalyzer
from flask_cors import CORS
import uuid
import hashlib
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

# -------------------- App Setup --------------------

app = Flask(__name__)
CORS(app)

BASE_URL = os.environ.get("BASE_URL", "http://localhost:5000")

UPLOAD_FOLDER = 'uploads'
CERT_FOLDER = 'certificates'

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(CERT_FOLDER, exist_ok=True)

# -------------------- Engines --------------------

aadhaar_engine = AadhaarAnalyzer()

# -------------------- Utilities --------------------

def calculate_sha256(filepath):
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def generate_certificate(cert_id, filename, file_hash, analysis_type, timestamp):
    cert_path = os.path.join(CERT_FOLDER, f"{cert_id}.pdf")
    c = canvas.Canvas(cert_path, pagesize=letter)
    width, height = letter

    c.setStrokeColor(colors.darkblue)
    c.setLineWidth(5)
    c.rect(30, 30, width - 60, height - 60)

    c.setFont("Helvetica-Bold", 30)
    c.drawCentredString(width / 2, height - 100, "CERTIFICATE OF ANALYSIS")

    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 130, "Sicario Forensic Document Analyzer")

    y_pos = height - 200

    def draw(label, value):
        nonlocal y_pos
        c.setFont("Helvetica-Bold", 14)
        c.drawString(100, y_pos, label)
        c.setFont("Helvetica", 14)
        c.drawString(250, y_pos, value)
        y_pos -= 40

    draw("Reference ID:", cert_id)
    draw("File Name:", filename)
    draw("Analysis Type:", analysis_type)
    draw("Timestamp:", timestamp)

    y_pos -= 20
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y_pos, "SHA-256 Secure Hash:")
    c.setFont("Courier", 10)
    c.drawString(100, y_pos - 20, file_hash)

    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 60, "This document certifies that the above file has undergone forensic analysis.")
    c.drawCentredString(width / 2, 45, "Generated by Sicario Secure Layer")

    c.save()
    return f"{cert_id}.pdf"

# -------------------- Routes --------------------

@app.route("/health")
def health():
    return {"status": "ok"}

@app.route('/analyze', methods=['POST'])
def analyze_document():
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400

    file = request.files['file']
    doc_type = request.form.get('doc_type', 'marksheet')

    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400

    filename = f"{uuid.uuid4()}_{file.filename}"
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    file.save(filepath)

    try:
        file_hash = calculate_sha256(filepath)
        cert_id = str(uuid.uuid4()).upper()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        response_data = {}

        if doc_type == 'aadhaar':
            result = aadhaar_engine.analyze(filepath)

            response_data = {
                "filename": file.filename,
                "checks": {
                    "Aadhaar Number": {
                        "status": result["status"],
                        "details": result["details"]
                    },
                    "Structural Check": {
                        "status": "Pass" if result["verhoeff_valid"] else "Fail",
                        "details": "Verhoeff Algorithm Validation"
                    },
                    "Database Check": {
                        "status": "Pass" if result["db_valid"] else "Fail",
                        "details": "ID existence in authorized DB"
                    }
                },
                "ela_url": None
            }

        elif doc_type == 'bills':
            response_data = {
                "filename": file.filename,
                "checks": {
                    "Digital Tampering (ELA)": {
                        "status": "Fail",
                        "details": "High compression artifacts detected near 'Total Amount' field."
                    },
                    "Metadata Analysis": {
                        "status": "Warn",
                        "details": "Software: 'Adobe Photoshop 2024' found in EXIF tags."
                    },
                    "Font Consistency": {
                        "status": "Fail",
                        "details": "Detected multiple font families (Arial, Times New Roman) in same line."
                    },
                    "Tax Calculation": {
                        "status": "Pass",
                        "details": "GST 18% calculation is mathematically correct."
                    }
                },
                "ela_url": None
            }

        else:
            detector = ForgeryDetector(filepath)
            detector.perform_ela(output_dir=UPLOAD_FOLDER)
            detector.check_metadata()
            detector.verify_logical_consistency()

            response_data = detector.report_data

            if response_data.get("ela_path"):
                response_data["ela_url"] = f"{BASE_URL}/uploads/{response_data['ela_path']}"

        cert_filename = generate_certificate(cert_id, file.filename, file_hash, doc_type.upper(), timestamp)

        response_data["security"] = {
            "file_hash": file_hash,
            "cert_id": cert_id,
            "cert_url": f"{BASE_URL}/certificates/{cert_filename}"
        }

        return jsonify(response_data)

    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_file(os.path.join(UPLOAD_FOLDER, filename))

@app.route('/certificates/<filename>')
def serve_certificate(filename):
    return send_file(os.path.join(CERT_FOLDER, filename))

# -------------------- Entry --------------------

# Gunicorn will start the server in production.
# No app.run() needed here.
